app = 'priagram'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.23.4'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1025
